const universitiesData = [

  // ==================== USA (40) ====================
  {
    name: "Hartwick College",
    location: "Oneonta, New York",
    country: "USA",
    tuition: "$25,000–$35,000 / year",
    scholarship: "Up to $32,000 / year",
    ielts: "Not Required",
    intakes: "September, January",
    programs: ["Business Administration", "Computer Science", "Biology", "Psychology", "Nursing"],
    tag: "Affordable",
    website: "https://www.hartwick.edu"
  },
  {
    name: "Pace University",
    location: "New York City, New York",
    country: "USA",
    tuition: "$48,000–$55,000 / year",
    scholarship: "Up to $30,000 / year",
    ielts: "IELTS 6.0 or Duolingo 105",
    intakes: "September, January",
    programs: ["Finance", "Marketing", "Nursing", "Computer Science", "Law"],
    tag: "NYC",
    website: "https://www.pace.edu"
  },
  {
    name: "Monroe University",
    location: "Bronx, New York",
    country: "USA",
    tuition: "$15,000–$25,000 / year",
    scholarship: "Up to $3,500 / semester",
    ielts: "Not Required",
    intakes: "September, January, May",
    programs: ["Business Administration", "Criminal Justice", "Computer Science", "Hospitality", "Healthcare"],
    tag: "Fast Admissions",
    website: "https://www.monroecollege.edu"
  },
  {
    name: "University of Bridgeport",
    location: "Bridgeport, Connecticut",
    country: "USA",
    tuition: "$30,000–$38,000 / year",
    scholarship: "Up to $18,000 / year",
    ielts: "IELTS 6.0 or Duolingo 95",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Computer Science", "Dental Hygiene", "Design"],
    tag: "Scholarship",
    website: "https://www.bridgeport.edu"
  },
  {
    name: "Mercy University",
    location: "Dobbs Ferry, New York",
    country: "USA",
    tuition: "$22,000–$28,000 / year",
    scholarship: "Up to $15,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Nursing", "Business", "Education", "Psychology", "Computer Science"],
    tag: "Affordable",
    website: "https://www.mercy.edu"
  },
  {
    name: "CUNY Brooklyn College",
    location: "Brooklyn, New York",
    country: "USA",
    tuition: "$7,000–$18,000 / year",
    scholarship: "Merit-based awards available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Computer Science", "Film", "Psychology", "Biology"],
    tag: "Affordable",
    website: "https://www.brooklyn.cuny.edu"
  },
  {
    name: "Adelphi University",
    location: "Garden City, New York",
    country: "USA",
    tuition: "$40,000–$46,000 / year",
    scholarship: "Up to $22,000 / year",
    ielts: "IELTS 6.0 or Duolingo 100",
    intakes: "September, January",
    programs: ["Nursing", "Business", "Social Work", "Education", "Psychology"],
    tag: "Scholarship",
    website: "https://www.adelphi.edu"
  },
  {
    name: "Long Island University",
    location: "Brooklyn, New York",
    country: "USA",
    tuition: "$38,000–$44,000 / year",
    scholarship: "Up to $20,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Pharmacy", "Business", "Health Sciences", "Education", "Computer Science"],
    tag: "NYC",
    website: "https://www.liu.edu"
  },
  {
    name: "St. John's University",
    location: "Queens, New York",
    country: "USA",
    tuition: "$42,000–$48,000 / year",
    scholarship: "Up to $25,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Pharmacy", "Law", "Education", "Computer Science"],
    tag: "NYC",
    website: "https://www.stjohns.edu"
  },
  {
    name: "Fordham University",
    location: "Bronx, New York",
    country: "USA",
    tuition: "$55,000–$60,000 / year",
    scholarship: "Up to $28,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Law", "Social Work", "Communications", "Psychology"],
    tag: "Top Ranked",
    website: "https://www.fordham.edu"
  },
  {
    name: "Hofstra University",
    location: "Hempstead, New York",
    country: "USA",
    tuition: "$48,000–$54,000 / year",
    scholarship: "Up to $24,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Law", "Engineering", "Education", "Health Sciences"],
    tag: "Scholarship",
    website: "https://www.hofstra.edu"
  },
  {
    name: "Manhattanville University",
    location: "Purchase, New York",
    country: "USA",
    tuition: "$38,000–$43,000 / year",
    scholarship: "Up to $20,000 / year",
    ielts: "IELTS 6.0 or Duolingo 95",
    intakes: "September, January",
    programs: ["Business", "Education", "Sport Management", "Arts", "Psychology"],
    tag: "Affordable",
    website: "https://www.mville.edu"
  },
  {
    name: "Sacred Heart University",
    location: "Fairfield, Connecticut",
    country: "USA",
    tuition: "$44,000–$50,000 / year",
    scholarship: "Up to $22,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Nursing", "Business", "Physical Therapy", "Communication", "Computer Science"],
    tag: "Health",
    website: "https://www.sacredheart.edu"
  },
  {
    name: "Fairleigh Dickinson University",
    location: "Teaneck, New Jersey",
    country: "USA",
    tuition: "$36,000–$42,000 / year",
    scholarship: "Up to $18,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Hospitality", "Psychology", "Computer Science"],
    tag: "Affordable",
    website: "https://www.fdu.edu"
  },
  {
    name: "Rutgers University",
    location: "Newark, New Jersey",
    country: "USA",
    tuition: "$30,000–$40,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Law", "Engineering", "Nursing", "Public Affairs"],
    tag: "Top Ranked",
    website: "https://www.rutgers.edu"
  },
  {
    name: "New Jersey City University",
    location: "Jersey City, New Jersey",
    country: "USA",
    tuition: "$12,000–$20,000 / year",
    scholarship: "Need-based and merit awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Education", "Nursing", "Criminal Justice", "Computer Science"],
    tag: "Affordable",
    website: "https://www.njcu.edu"
  },
  {
    name: "American University",
    location: "Washington, D.C.",
    country: "USA",
    tuition: "$52,000–$58,000 / year",
    scholarship: "Up to $30,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["International Relations", "Business", "Law", "Communications", "Political Science"],
    tag: "Top Ranked",
    website: "https://www.american.edu"
  },
  {
    name: "George Mason University",
    location: "Fairfax, Virginia",
    country: "USA",
    tuition: "$35,000–$42,000 / year",
    scholarship: "Partial merit scholarships",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Computer Science", "Engineering", "Business", "Public Policy", "Cybersecurity"],
    tag: "Technology",
    website: "https://www.gmu.edu"
  },
  {
    name: "University of New Haven",
    location: "West Haven, Connecticut",
    country: "USA",
    tuition: "$40,000–$46,000 / year",
    scholarship: "Up to $20,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Criminal Justice", "Engineering", "Business", "Forensic Science", "Computer Science"],
    tag: "Scholarship",
    website: "https://www.newhaven.edu"
  },
  {
    name: "Quinnipiac University",
    location: "Hamden, Connecticut",
    country: "USA",
    tuition: "$48,000–$53,000 / year",
    scholarship: "Up to $22,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Nursing", "Business", "Journalism", "Health Sciences", "Law"],
    tag: "Health",
    website: "https://www.qu.edu"
  },
  {
    name: "Western New England University",
    location: "Springfield, Massachusetts",
    country: "USA",
    tuition: "$36,000–$42,000 / year",
    scholarship: "Up to $20,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Law", "Pharmacy", "Computer Science"],
    tag: "Affordable",
    website: "https://www.wne.edu"
  },
  {
    name: "Suffolk University",
    location: "Boston, Massachusetts",
    country: "USA",
    tuition: "$42,000–$48,000 / year",
    scholarship: "Up to $18,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Law", "Communications", "Public Administration", "Finance"],
    tag: "Business",
    website: "https://www.suffolk.edu"
  },
  {
    name: "Northeastern University",
    location: "Boston, Massachusetts",
    country: "USA",
    tuition: "$58,000–$63,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Computer Science", "Engineering", "Business", "Health Sciences", "Law"],
    tag: "Top Ranked",
    website: "https://www.northeastern.edu"
  },
  {
    name: "University of Massachusetts Boston",
    location: "Boston, Massachusetts",
    country: "USA",
    tuition: "$28,000–$35,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Computer Science", "Nursing", "Psychology", "Engineering"],
    tag: "Affordable",
    website: "https://www.umb.edu"
  },
  {
    name: "Clark University",
    location: "Worcester, Massachusetts",
    country: "USA",
    tuition: "$46,000–$52,000 / year",
    scholarship: "Up to $25,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Psychology", "Business", "Geography", "International Development", "Computer Science"],
    tag: "Research",
    website: "https://www.clarku.edu"
  },
  {
    name: "University of Illinois Chicago",
    location: "Chicago, Illinois",
    country: "USA",
    tuition: "$28,000–$38,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Health Sciences", "Architecture", "Computer Science"],
    tag: "Technology",
    website: "https://www.uic.edu"
  },
  {
    name: "DePaul University",
    location: "Chicago, Illinois",
    country: "USA",
    tuition: "$40,000–$46,000 / year",
    scholarship: "Up to $18,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Computer Science", "Law", "Education", "Communications"],
    tag: "Business",
    website: "https://www.depaul.edu"
  },
  {
    name: "Loyola University Chicago",
    location: "Chicago, Illinois",
    country: "USA",
    tuition: "$46,000–$52,000 / year",
    scholarship: "Up to $22,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Nursing", "Law", "Social Work", "Psychology"],
    tag: "Top Ranked",
    website: "https://www.luc.edu"
  },
  {
    name: "University of Houston",
    location: "Houston, Texas",
    country: "USA",
    tuition: "$22,000–$32,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Engineering", "Business", "Law", "Architecture", "Computer Science"],
    tag: "Affordable",
    website: "https://www.uh.edu"
  },
  {
    name: "Texas Southern University",
    location: "Houston, Texas",
    country: "USA",
    tuition: "$10,000–$18,000 / year",
    scholarship: "Up to $8,000 / year",
    ielts: "IELTS 5.5",
    intakes: "September, January",
    programs: ["Business", "Law", "Pharmacy", "Engineering", "Education"],
    tag: "Affordable",
    website: "https://www.tsu.edu"
  },
  {
    name: "University of North Texas",
    location: "Denton, Texas",
    country: "USA",
    tuition: "$18,000–$28,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Music", "Computer Science", "Engineering", "Psychology"],
    tag: "Affordable",
    website: "https://www.unt.edu"
  },
  {
    name: "University of Arizona",
    location: "Tucson, Arizona",
    country: "USA",
    tuition: "$33,000–$40,000 / year",
    scholarship: "Up to $15,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Astronomy", "Computer Science", "Public Health"],
    tag: "Research",
    website: "https://www.arizona.edu"
  },
  {
    name: "Arizona State University",
    location: "Tempe, Arizona",
    country: "USA",
    tuition: "$28,000–$36,000 / year",
    scholarship: "Up to $12,000 / year",
    ielts: "IELTS 6.0 or Duolingo 95",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Computer Science", "Journalism", "Design"],
    tag: "Top Ranked",
    website: "https://www.asu.edu"
  },
  {
    name: "University of Nevada Las Vegas",
    location: "Las Vegas, Nevada",
    country: "USA",
    tuition: "$20,000–$28,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Hospitality", "Business", "Engineering", "Health Sciences", "Computer Science"],
    tag: "Affordable",
    website: "https://www.unlv.edu"
  },
  {
    name: "San Francisco State University",
    location: "San Francisco, California",
    country: "USA",
    tuition: "$18,000–$26,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Computer Science", "Arts", "Education"],
    tag: "Affordable",
    website: "https://www.sfsu.edu"
  },
  {
    name: "California State University Los Angeles",
    location: "Los Angeles, California",
    country: "USA",
    tuition: "$16,000–$24,000 / year",
    scholarship: "Need and merit-based awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Computer Science", "Education", "Health Sciences"],
    tag: "Affordable",
    website: "https://www.calstatela.edu"
  },
  {
    name: "University of Oregon",
    location: "Eugene, Oregon",
    country: "USA",
    tuition: "$34,000–$42,000 / year",
    scholarship: "Up to $14,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September",
    programs: ["Business", "Journalism", "Architecture", "Psychology", "Computer Science"],
    tag: "Research",
    website: "https://www.uoregon.edu"
  },
  {
    name: "Portland State University",
    location: "Portland, Oregon",
    country: "USA",
    tuition: "$22,000–$30,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Urban Planning", "Computer Science", "Education"],
    tag: "Affordable",
    website: "https://www.pdx.edu"
  },
  {
    name: "Wayne State University",
    location: "Detroit, Michigan",
    country: "USA",
    tuition: "$18,000–$28,000 / year",
    scholarship: "Merit and need-based awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Medicine", "Law", "Computer Science"],
    tag: "Research",
    website: "https://www.wayne.edu"
  },
  {
    name: "Bowling Green State University",
    location: "Bowling Green, Ohio",
    country: "USA",
    tuition: "$18,000–$26,000 / year",
    scholarship: "Up to $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Education", "Computer Science", "Arts", "Psychology"],
    tag: "Affordable",
    website: "https://www.bgsu.edu"
  },

  // ==================== UK (40) ====================
  {
    name: "University of Hertfordshire",
    location: "Hatfield, England",
    country: "UK",
    tuition: "£13,000–£16,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Computer Science", "Pharmacy", "Law"],
    tag: "Affordable",
    website: "https://www.herts.ac.uk"
  },
  {
    name: "University of Chester",
    location: "Chester, England",
    country: "UK",
    tuition: "£12,500–£15,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Nursing", "Education", "Psychology", "Sports Science"],
    tag: "Affordable",
    website: "https://www.chester.ac.uk"
  },
  {
    name: "De Montfort University",
    location: "Leicester, England",
    country: "UK",
    tuition: "£13,000–£16,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Fashion", "Engineering", "Law", "Business", "Computer Science"],
    tag: "Arts",
    website: "https://www.dmu.ac.uk"
  },
  {
    name: "University of East London",
    location: "London, England",
    country: "UK",
    tuition: "£13,500–£16,500 / year",
    scholarship: "Up to £5,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Psychology", "Architecture", "Health Sciences", "Education"],
    tag: "Scholarship",
    website: "https://www.uel.ac.uk"
  },
  {
    name: "Middlesex University",
    location: "London, England",
    country: "UK",
    tuition: "£13,500–£17,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Law", "Arts & Design", "Health", "Engineering"],
    tag: "Affordable",
    website: "https://www.mdx.ac.uk"
  },
  {
    name: "London South Bank University",
    location: "London, England",
    country: "UK",
    tuition: "£14,000–£17,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Nursing", "Business", "Architecture", "Computer Science"],
    tag: "Affordable",
    website: "https://www.lsbu.ac.uk"
  },
  {
    name: "Anglia Ruskin University",
    location: "Cambridge, England",
    country: "UK",
    tuition: "£12,000–£15,000 / year",
    scholarship: "Up to £3,500 / year",
    ielts: "IELTS 5.5",
    intakes: "September, January",
    programs: ["Business", "Nursing", "Computer Science", "Law", "Psychology"],
    tag: "Affordable",
    website: "https://www.aru.ac.uk"
  },
  {
    name: "Coventry University",
    location: "Coventry, England",
    country: "UK",
    tuition: "£14,000–£17,500 / year",
    scholarship: "Up to £2,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Health", "Computing", "Architecture"],
    tag: "Technology",
    website: "https://www.coventry.ac.uk"
  },
  {
    name: "University of Wolverhampton",
    location: "Wolverhampton, England",
    country: "UK",
    tuition: "£12,500–£15,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Nursing", "Computer Science", "Education"],
    tag: "Affordable",
    website: "https://www.wlv.ac.uk"
  },
  {
    name: "University of Sunderland",
    location: "Sunderland, England",
    country: "UK",
    tuition: "£11,500–£14,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 5.5",
    intakes: "September, January",
    programs: ["Business", "Pharmacy", "Computing", "Health Sciences", "Engineering"],
    tag: "Affordable",
    website: "https://www.sunderland.ac.uk"
  },
  {
    name: "Teesside University",
    location: "Middlesbrough, England",
    country: "UK",
    tuition: "£12,000–£15,000 / year",
    scholarship: "Up to £2,500 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Computer Science", "Engineering", "Business", "Health", "Arts"],
    tag: "Technology",
    website: "https://www.tees.ac.uk"
  },
  {
    name: "University of Lincoln",
    location: "Lincoln, England",
    country: "UK",
    tuition: "£13,000–£16,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September",
    programs: ["Engineering", "Business", "Arts", "Computer Science", "Law"],
    tag: "Research",
    website: "https://www.lincoln.ac.uk"
  },
  {
    name: "Northumbria University",
    location: "Newcastle, England",
    country: "UK",
    tuition: "£14,000–£17,500 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Law", "Business", "Architecture", "Engineering", "Computer Science"],
    tag: "Scholarship",
    website: "https://www.northumbria.ac.uk"
  },
  {
    name: "University of Huddersfield",
    location: "Huddersfield, England",
    country: "UK",
    tuition: "£13,000–£16,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Music", "Computer Science", "Pharmacy"],
    tag: "Affordable",
    website: "https://www.hud.ac.uk"
  },
  {
    name: "University of Bolton",
    location: "Bolton, England",
    country: "UK",
    tuition: "£11,000–£13,500 / year",
    scholarship: "Up to £2,000 / year",
    ielts: "IELTS 5.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Education", "Computing", "Health"],
    tag: "Affordable",
    website: "https://www.bolton.ac.uk"
  },
  {
    name: "University of Central Lancashire",
    location: "Preston, England",
    country: "UK",
    tuition: "£12,500–£15,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Journalism", "Nursing", "Business", "Engineering", "Law"],
    tag: "Affordable",
    website: "https://www.uclan.ac.uk"
  },
  {
    name: "Sheffield Hallam University",
    location: "Sheffield, England",
    country: "UK",
    tuition: "£13,500–£16,500 / year",
    scholarship: "Up to £3,500 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Health", "Arts", "Computer Science"],
    tag: "Scholarship",
    website: "https://www.shu.ac.uk"
  },
  {
    name: "Leeds Beckett University",
    location: "Leeds, England",
    country: "UK",
    tuition: "£12,500–£15,500 / year",
    scholarship: "Up to £2,500 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Sport", "Nursing", "Law", "Film"],
    tag: "Affordable",
    website: "https://www.leedsbeckett.ac.uk"
  },
  {
    name: "University of Bradford",
    location: "Bradford, England",
    country: "UK",
    tuition: "£13,000–£16,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Pharmacy", "Computer Science", "Peace Studies"],
    tag: "Research",
    website: "https://www.bradford.ac.uk"
  },
  {
    name: "Manchester Metropolitan University",
    location: "Manchester, England",
    country: "UK",
    tuition: "£14,000–£17,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Arts", "Law", "Education"],
    tag: "Scholarship",
    website: "https://www.mmu.ac.uk"
  },
  {
    name: "University of Salford",
    location: "Salford, England",
    country: "UK",
    tuition: "£13,500–£17,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Nursing", "Media", "Computer Science"],
    tag: "Technology",
    website: "https://www.salford.ac.uk"
  },
  {
    name: "University of Derby",
    location: "Derby, England",
    country: "UK",
    tuition: "£12,500–£15,000 / year",
    scholarship: "Up to £2,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Psychology", "Education", "Arts"],
    tag: "Affordable",
    website: "https://www.derby.ac.uk"
  },
  {
    name: "University of Greenwich",
    location: "London, England",
    country: "UK",
    tuition: "£14,000–£17,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Computing", "Architecture", "Health"],
    tag: "Affordable",
    website: "https://www.gre.ac.uk"
  },
  {
    name: "University of Westminster",
    location: "London, England",
    country: "UK",
    tuition: "£14,500–£17,500 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Law", "Media", "Architecture", "Computer Science"],
    tag: "Scholarship",
    website: "https://www.westminster.ac.uk"
  },
  {
    name: "Brunel University London",
    location: "London, England",
    country: "UK",
    tuition: "£18,000–£22,000 / year",
    scholarship: "Up to £6,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September",
    programs: ["Engineering", "Business", "Law", "Computer Science", "Health"],
    tag: "Top Ranked",
    website: "https://www.brunel.ac.uk"
  },
  {
    name: "Kingston University London",
    location: "Kingston upon Thames, London",
    country: "UK",
    tuition: "£14,000–£17,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Architecture", "Business", "Law", "Arts", "Computer Science"],
    tag: "Arts",
    website: "https://www.kingston.ac.uk"
  },
  {
    name: "University of Roehampton",
    location: "London, England",
    country: "UK",
    tuition: "£13,500–£16,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Psychology", "Business", "Education", "Sports Science", "Media"],
    tag: "Affordable",
    website: "https://www.roehampton.ac.uk"
  },
  {
    name: "University of Bedfordshire",
    location: "Luton, England",
    country: "UK",
    tuition: "£11,500–£14,000 / year",
    scholarship: "Up to £2,000 / year",
    ielts: "IELTS 5.5",
    intakes: "September, January",
    programs: ["Business", "Computing", "Education", "Nursing", "Media"],
    tag: "Affordable",
    website: "https://www.beds.ac.uk"
  },
  {
    name: "University of East Anglia",
    location: "Norwich, England",
    country: "UK",
    tuition: "£18,000–£22,000 / year",
    scholarship: "Up to £5,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September",
    programs: ["Law", "Business", "Environmental Science", "Medicine", "Literature"],
    tag: "Research",
    website: "https://www.uea.ac.uk"
  },
  {
    name: "University of Surrey",
    location: "Guildford, England",
    country: "UK",
    tuition: "£18,000–£23,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September",
    programs: ["Engineering", "Hospitality", "Business", "Computer Science", "Health"],
    tag: "Top Ranked",
    website: "https://www.surrey.ac.uk"
  },
  {
    name: "University of Leicester",
    location: "Leicester, England",
    country: "UK",
    tuition: "£18,000–£22,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September",
    programs: ["Medicine", "Law", "Business", "Space Science", "Psychology"],
    tag: "Research",
    website: "https://www.le.ac.uk"
  },
  {
    name: "University of Essex",
    location: "Colchester, England",
    country: "UK",
    tuition: "£15,000–£19,000 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Economics", "Political Science", "Law", "Computer Science", "Psychology"],
    tag: "Research",
    website: "https://www.essex.ac.uk"
  },
  {
    name: "Bournemouth University",
    location: "Bournemouth, England",
    country: "UK",
    tuition: "£14,000–£17,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September",
    programs: ["Media", "Tourism", "Business", "Computing", "Health"],
    tag: "Arts",
    website: "https://www.bournemouth.ac.uk"
  },
  {
    name: "Swansea University",
    location: "Swansea, Wales",
    country: "UK",
    tuition: "£14,000–£18,000 / year",
    scholarship: "Up to £5,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Law", "Medicine", "Computer Science"],
    tag: "Scholarship",
    website: "https://www.swansea.ac.uk"
  },
  {
    name: "Cardiff Metropolitan University",
    location: "Cardiff, Wales",
    country: "UK",
    tuition: "£13,000–£15,500 / year",
    scholarship: "Up to £2,500 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Sport", "Business", "Art & Design", "Education", "Health"],
    tag: "Affordable",
    website: "https://www.cardiffmet.ac.uk"
  },
  {
    name: "University of the West of Scotland",
    location: "Paisley, Scotland",
    country: "UK",
    tuition: "£12,000–£15,000 / year",
    scholarship: "Up to £2,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Computing", "Engineering", "Business", "Nursing", "Law"],
    tag: "Affordable",
    website: "https://www.uws.ac.uk"
  },
  {
    name: "Edinburgh Napier University",
    location: "Edinburgh, Scotland",
    country: "UK",
    tuition: "£14,000–£17,500 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Computing", "Engineering", "Nursing", "Tourism"],
    tag: "Technology",
    website: "https://www.napier.ac.uk"
  },
  {
    name: "Robert Gordon University",
    location: "Aberdeen, Scotland",
    country: "UK",
    tuition: "£13,500–£17,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September",
    programs: ["Oil & Gas Engineering", "Nursing", "Business", "Architecture", "Pharmacy"],
    tag: "Technology",
    website: "https://www.rgu.ac.uk"
  },
  {
    name: "Glasgow Caledonian University",
    location: "Glasgow, Scotland",
    country: "UK",
    tuition: "£13,000–£16,000 / year",
    scholarship: "Up to £3,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September",
    programs: ["Business", "Nursing", "Engineering", "Computer Science", "Social Work"],
    tag: "Affordable",
    website: "https://www.gcu.ac.uk"
  },
  {
    name: "Nottingham Trent University",
    location: "Nottingham, England",
    country: "UK",
    tuition: "£14,500–£17,500 / year",
    scholarship: "Up to £4,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Law", "Business", "Fashion", "Architecture", "Computer Science"],
    tag: "Top Ranked",
    website: "https://www.ntu.ac.uk"
  },

  // ==================== CANADA (40) ====================
  {
    name: "Seneca Polytechnic",
    location: "Toronto, Ontario",
    country: "Canada",
    tuition: "CAD $16,000–$20,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Business", "Computer Science", "Engineering Technology", "Accounting", "Marketing"],
    tag: "Fast Admissions",
    website: "https://www.senecapolytechnic.ca"
  },
  {
    name: "Humber College",
    location: "Toronto, Ontario",
    country: "Canada",
    tuition: "CAD $16,500–$21,000 / year",
    scholarship: "International entrance awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Media", "Engineering Technology", "Health Sciences", "Hospitality"],
    tag: "Affordable",
    website: "https://www.humber.ca"
  },
  {
    name: "Algonquin College",
    location: "Ottawa, Ontario",
    country: "Canada",
    tuition: "CAD $15,000–$20,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "IT", "Health Sciences", "Media", "Engineering Technology"],
    tag: "Affordable",
    website: "https://www.algonquincollege.com"
  },
  {
    name: "Conestoga College",
    location: "Kitchener, Ontario",
    country: "Canada",
    tuition: "CAD $15,500–$20,500 / year",
    scholarship: "Entrance scholarships available",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Engineering Technology", "Business", "IT", "Health Sciences", "Trades"],
    tag: "Technology",
    website: "https://www.conestogac.on.ca"
  },
  {
    name: "George Brown College",
    location: "Toronto, Ontario",
    country: "Canada",
    tuition: "CAD $16,000–$22,000 / year",
    scholarship: "Bursaries and awards available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Culinary Arts", "Business", "Health Sciences", "Design", "Computing"],
    tag: "Fast Admissions",
    website: "https://www.georgebrown.ca"
  },
  {
    name: "Fanshawe College",
    location: "London, Ontario",
    country: "Canada",
    tuition: "CAD $14,500–$18,500 / year",
    scholarship: "International student awards",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Business", "Engineering Technology", "Media", "Social Services", "IT"],
    tag: "Affordable",
    website: "https://www.fanshawec.ca"
  },
  {
    name: "Lambton College",
    location: "Sarnia, Ontario",
    country: "Canada",
    tuition: "CAD $14,000–$17,500 / year",
    scholarship: "Up to CAD $2,000 / year",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Business", "Engineering", "IT", "Fire & Public Safety", "Health"],
    tag: "Affordable",
    website: "https://www.lambtoncollege.ca"
  },
  {
    name: "Mohawk College",
    location: "Hamilton, Ontario",
    country: "Canada",
    tuition: "CAD $14,500–$18,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering Technology", "Health Sciences", "IT", "Media"],
    tag: "Affordable",
    website: "https://www.mohawkcollege.ca"
  },
  {
    name: "Sheridan College",
    location: "Brampton, Ontario",
    country: "Canada",
    tuition: "CAD $16,000–$21,000 / year",
    scholarship: "International entrance awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Animation", "Business", "Engineering Technology", "Design", "Computer Science"],
    tag: "Arts",
    website: "https://www.sheridancollege.ca"
  },
  {
    name: "Centennial College",
    location: "Toronto, Ontario",
    country: "Canada",
    tuition: "CAD $15,500–$20,000 / year",
    scholarship: "Bursaries available",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Engineering Technology", "Business", "Health Sciences", "Aviation", "Media"],
    tag: "Technology",
    website: "https://www.centennialcollege.ca"
  },
  {
    name: "Durham College",
    location: "Oshawa, Ontario",
    country: "Canada",
    tuition: "CAD $14,500–$18,000 / year",
    scholarship: "Entrance scholarships",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "IT", "Engineering", "Nursing", "Culinary"],
    tag: "Affordable",
    website: "https://www.durhamcollege.ca"
  },
  {
    name: "BCIT (BC Institute of Technology)",
    location: "Burnaby, British Columbia",
    country: "Canada",
    tuition: "CAD $14,000–$20,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Health Sciences", "Computing", "Trades"],
    tag: "Technology",
    website: "https://www.bcit.ca"
  },
  {
    name: "Langara College",
    location: "Vancouver, British Columbia",
    country: "Canada",
    tuition: "CAD $14,500–$19,000 / year",
    scholarship: "Entrance awards available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Computing Science", "Health Sciences", "Liberal Arts", "Accounting"],
    tag: "Affordable",
    website: "https://www.langara.ca"
  },
  {
    name: "Kwantlen Polytechnic University",
    location: "Surrey, British Columbia",
    country: "Canada",
    tuition: "CAD $15,000–$19,500 / year",
    scholarship: "International entrance scholarships",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Engineering Technology", "Horticulture", "Health Sciences", "Design"],
    tag: "Affordable",
    website: "https://www.kpu.ca"
  },
  {
    name: "Vancouver Island University",
    location: "Nanaimo, British Columbia",
    country: "Canada",
    tuition: "CAD $16,000–$19,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Tourism", "Computer Science", "Education", "Nursing"],
    tag: "Affordable",
    website: "https://www.viu.ca"
  },
  {
    name: "Capilano University",
    location: "North Vancouver, British Columbia",
    country: "Canada",
    tuition: "CAD $16,500–$20,000 / year",
    scholarship: "Entrance awards available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Tourism", "Arts", "Music", "Legal Studies"],
    tag: "Arts",
    website: "https://www.capilanou.ca"
  },
  {
    name: "NAIT (Northern Alberta Institute of Technology)",
    location: "Edmonton, Alberta",
    country: "Canada",
    tuition: "CAD $14,000–$18,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering Technology", "Business", "Health Sciences", "IT", "Trades"],
    tag: "Technology",
    website: "https://www.nait.ca"
  },
  {
    name: "SAIT (Southern Alberta Institute of Technology)",
    location: "Calgary, Alberta",
    country: "Canada",
    tuition: "CAD $15,000–$19,000 / year",
    scholarship: "International student awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Engineering Technology", "Business", "Culinary Arts", "IT", "Health Sciences"],
    tag: "Technology",
    website: "https://www.sait.ca"
  },
  {
    name: "MacEwan University",
    location: "Edmonton, Alberta",
    country: "Canada",
    tuition: "CAD $16,000–$20,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Nursing", "Arts", "Education", "Computing Science"],
    tag: "Affordable",
    website: "https://www.macewan.ca"
  },
  {
    name: "Mount Royal University",
    location: "Calgary, Alberta",
    country: "Canada",
    tuition: "CAD $16,500–$20,500 / year",
    scholarship: "Entrance scholarships",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Nursing", "Communication", "Computer Science", "Social Work"],
    tag: "Scholarship",
    website: "https://www.mtroyal.ca"
  },
  {
    name: "Red River College Polytechnic",
    location: "Winnipeg, Manitoba",
    country: "Canada",
    tuition: "CAD $13,000–$17,500 / year",
    scholarship: "Bursaries and awards",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "Engineering Technology", "IT", "Health Sciences", "Culinary Arts"],
    tag: "Affordable",
    website: "https://www.rrc.ca"
  },
  {
    name: "University of Winnipeg",
    location: "Winnipeg, Manitoba",
    country: "Canada",
    tuition: "CAD $13,000–$16,000 / year",
    scholarship: "International entrance awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Arts", "Psychology", "Biology", "Computer Science"],
    tag: "Affordable",
    website: "https://www.uwinnipeg.ca"
  },
  {
    name: "Nova Scotia Community College",
    location: "Halifax, Nova Scotia",
    country: "Canada",
    tuition: "CAD $12,500–$16,000 / year",
    scholarship: "Entrance scholarships",
    ielts: "IELTS 6.0",
    intakes: "September, January",
    programs: ["Business", "IT", "Health Sciences", "Engineering Technology", "Trades"],
    tag: "Affordable",
    website: "https://www.nscc.ca"
  },
  {
    name: "Saint Mary's University",
    location: "Halifax, Nova Scotia",
    country: "Canada",
    tuition: "CAD $17,000–$21,000 / year",
    scholarship: "Up to CAD $5,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Science", "Arts", "Criminology", "Computing"],
    tag: "Scholarship",
    website: "https://www.smu.ca"
  },
  {
    name: "Dalhousie University",
    location: "Halifax, Nova Scotia",
    country: "Canada",
    tuition: "CAD $22,000–$28,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Law", "Medicine", "Computer Science"],
    tag: "Top Ranked",
    website: "https://www.dal.ca"
  },
  {
    name: "University of New Brunswick",
    location: "Fredericton, New Brunswick",
    country: "Canada",
    tuition: "CAD $17,000–$22,000 / year",
    scholarship: "International student awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Computer Science", "Law", "Education"],
    tag: "Research",
    website: "https://www.unb.ca"
  },
  {
    name: "Memorial University of Newfoundland",
    location: "St. John's, Newfoundland",
    country: "Canada",
    tuition: "CAD $11,000–$15,000 / year",
    scholarship: "Up to CAD $5,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Medicine", "Ocean Sciences", "Education"],
    tag: "Affordable",
    website: "https://www.mun.ca"
  },
  {
    name: "University of Regina",
    location: "Regina, Saskatchewan",
    country: "Canada",
    tuition: "CAD $17,000–$21,000 / year",
    scholarship: "International entrance scholarships",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Engineering", "Education", "Social Work", "Computer Science"],
    tag: "Scholarship",
    website: "https://www.uregina.ca"
  },
  {
    name: "University of Saskatchewan",
    location: "Saskatoon, Saskatchewan",
    country: "Canada",
    tuition: "CAD $19,000–$24,000 / year",
    scholarship: "Merit-based scholarships",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Agriculture", "Medicine", "Law", "Business"],
    tag: "Research",
    website: "https://www.usask.ca"
  },
  {
    name: "Brock University",
    location: "St. Catharines, Ontario",
    country: "Canada",
    tuition: "CAD $26,000–$30,000 / year",
    scholarship: "Up to CAD $4,000 / year",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Education", "Kinesiology", "Computer Science", "Arts"],
    tag: "Scholarship",
    website: "https://www.brocku.ca"
  },
  {
    name: "Wilfrid Laurier University",
    location: "Waterloo, Ontario",
    country: "Canada",
    tuition: "CAD $28,000–$33,000 / year",
    scholarship: "International entrance awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Music", "Social Work", "Education", "Computer Science"],
    tag: "Business",
    website: "https://www.wlu.ca"
  },
  {
    name: "Trent University",
    location: "Peterborough, Ontario",
    country: "Canada",
    tuition: "CAD $24,000–$28,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.5",
    intakes: "September",
    programs: ["Environmental Science", "Business", "Psychology", "Indigenous Studies", "Computing"],
    tag: "Research",
    website: "https://www.trentu.ca"
  },
  {
    name: "Lakehead University",
    location: "Thunder Bay, Ontario",
    country: "Canada",
    tuition: "CAD $22,000–$26,000 / year",
    scholarship: "International entrance awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Engineering", "Business", "Education", "Law", "Computer Science"],
    tag: "Affordable",
    website: "https://www.lakeheadu.ca"
  },
  {
    name: "Nipissing University",
    location: "North Bay, Ontario",
    country: "Canada",
    tuition: "CAD $21,000–$25,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Education", "Business", "Nursing", "Arts", "Computer Science"],
    tag: "Affordable",
    website: "https://www.nipissingu.ca"
  },
  {
    name: "University of Prince Edward Island",
    location: "Charlottetown, PEI",
    country: "Canada",
    tuition: "CAD $15,000–$19,000 / year",
    scholarship: "Entrance scholarships",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Veterinary Medicine", "Nursing", "Education", "Arts"],
    tag: "Affordable",
    website: "https://www.upei.ca"
  },
  {
    name: "Thompson Rivers University",
    location: "Kamloops, British Columbia",
    country: "Canada",
    tuition: "CAD $18,000–$22,000 / year",
    scholarship: "International student awards",
    ielts: "IELTS 6.0",
    intakes: "September, January, May",
    programs: ["Business", "Nursing", "Engineering", "Law", "Education"],
    tag: "Fast Admissions",
    website: "https://www.tru.ca"
  },
  {
    name: "University of the Fraser Valley",
    location: "Abbotsford, British Columbia",
    country: "Canada",
    tuition: "CAD $17,000–$21,000 / year",
    scholarship: "Merit-based awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Computing", "Engineering Technology", "Health Sciences", "Education"],
    tag: "Affordable",
    website: "https://www.ufv.ca"
  },
  {
    name: "Athabasca University",
    location: "Athabasca, Alberta",
    country: "Canada",
    tuition: "CAD $14,000–$18,000 / year",
    scholarship: "Bursaries available",
    ielts: "IELTS 6.0",
    intakes: "Open enrollment",
    programs: ["Business", "Computing & Information Systems", "Psychology", "Nursing", "Education"],
    tag: "Fast Admissions",
    website: "https://www.athabascau.ca"
  },
  {
    name: "Concordia University of Edmonton",
    location: "Edmonton, Alberta",
    country: "Canada",
    tuition: "CAD $18,000–$22,000 / year",
    scholarship: "Entrance awards available",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Business", "Psychology", "Computing", "Arts", "Biology"],
    tag: "Affordable",
    website: "https://www.concordia.ab.ca"
  },
  {
    name: "Brandon University",
    location: "Brandon, Manitoba",
    country: "Canada",
    tuition: "CAD $14,000–$17,000 / year",
    scholarship: "International entrance awards",
    ielts: "IELTS 6.5",
    intakes: "September, January",
    programs: ["Music", "Education", "Business", "Science", "Arts"],
    tag: "Affordable",
    website: "https://www.brandonu.ca"
  },

  // ==================== AUSTRALIA (40) ====================
  {
    name: "RMIT University",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $30,000–$38,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "Design", "Computer Science", "Architecture"],
    tag: "Top Ranked",
    website: "https://www.rmit.edu.au"
  },
  {
    name: "Griffith University",
    location: "Brisbane, Queensland",
    country: "Australia",
    tuition: "AUD $26,000–$34,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Law", "Health Sciences", "Environment", "Arts"],
    tag: "Scholarship",
    website: "https://www.griffith.edu.au"
  },
  {
    name: "University of Southern Queensland",
    location: "Toowoomba, Queensland",
    country: "Australia",
    tuition: "AUD $22,000–$30,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "Education", "Nursing", "Computing"],
    tag: "Affordable",
    website: "https://www.unisq.edu.au"
  },
  {
    name: "Charles Darwin University",
    location: "Darwin, Northern Territory",
    country: "Australia",
    tuition: "AUD $20,000–$28,000 / year",
    scholarship: "Up to AUD $5,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Engineering", "Nursing", "Education", "Law"],
    tag: "Affordable",
    website: "https://www.cdu.edu.au"
  },
  {
    name: "Federation University Australia",
    location: "Ballarat, Victoria",
    country: "Australia",
    tuition: "AUD $22,000–$28,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "IT", "Education", "Health Sciences"],
    tag: "Affordable",
    website: "https://www.federation.edu.au"
  },
  {
    name: "Central Queensland University",
    location: "Rockhampton, Queensland",
    country: "Australia",
    tuition: "AUD $22,000–$29,000 / year",
    scholarship: "Up to AUD $6,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July, November",
    programs: ["Business", "Engineering", "Nursing", "Education", "IT"],
    tag: "Fast Admissions",
    website: "https://www.cqu.edu.au"
  },
  {
    name: "University of the Sunshine Coast",
    location: "Sippy Downs, Queensland",
    country: "Australia",
    tuition: "AUD $24,000–$30,000 / year",
    scholarship: "International merit awards",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Health Sciences", "Education", "Science", "Arts"],
    tag: "Affordable",
    website: "https://www.usc.edu.au"
  },
  {
    name: "James Cook University",
    location: "Townsville, Queensland",
    country: "Australia",
    tuition: "AUD $26,000–$34,000 / year",
    scholarship: "Up to AUD $6,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Marine Biology", "Business", "Education", "Medicine", "Engineering"],
    tag: "Research",
    website: "https://www.jcu.edu.au"
  },
  {
    name: "Edith Cowan University",
    location: "Perth, Western Australia",
    country: "Australia",
    tuition: "AUD $24,000–$31,000 / year",
    scholarship: "Up to AUD $5,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Engineering", "Nursing", "Education", "Arts"],
    tag: "Affordable",
    website: "https://www.ecu.edu.au"
  },
  {
    name: "Curtin University",
    location: "Perth, Western Australia",
    country: "Australia",
    tuition: "AUD $30,000–$38,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "Health Sciences", "Computing", "Architecture"],
    tag: "Top Ranked",
    website: "https://www.curtin.edu.au"
  },
  {
    name: "Murdoch University",
    location: "Perth, Western Australia",
    country: "Australia",
    tuition: "AUD $24,000–$32,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Veterinary Science", "Business", "Law", "Engineering", "IT"],
    tag: "Scholarship",
    website: "https://www.murdoch.edu.au"
  },
  {
    name: "University of Notre Dame Australia",
    location: "Fremantle, Western Australia",
    country: "Australia",
    tuition: "AUD $24,000–$30,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Nursing", "Business", "Law", "Education", "Philosophy"],
    tag: "Health",
    website: "https://www.notredame.edu.au"
  },
  {
    name: "University of Tasmania",
    location: "Hobart, Tasmania",
    country: "Australia",
    tuition: "AUD $24,000–$32,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Marine Science", "Business", "Engineering", "Law", "Education"],
    tag: "Research",
    website: "https://www.utas.edu.au"
  },
  {
    name: "Charles Sturt University",
    location: "Wagga Wagga, New South Wales",
    country: "Australia",
    tuition: "AUD $22,000–$28,000 / year",
    scholarship: "International student awards",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Agricultural Science", "Business", "Nursing", "IT", "Education"],
    tag: "Affordable",
    website: "https://www.csu.edu.au"
  },
  {
    name: "Southern Cross University",
    location: "Lismore, New South Wales",
    country: "Australia",
    tuition: "AUD $22,000–$28,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Nursing", "Education", "Law", "Environmental Science"],
    tag: "Affordable",
    website: "https://www.scu.edu.au"
  },
  {
    name: "Western Sydney University",
    location: "Penrith, New South Wales",
    country: "Australia",
    tuition: "AUD $25,000–$32,000 / year",
    scholarship: "International merit awards",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Engineering", "Nursing", "Law", "Education"],
    tag: "Scholarship",
    website: "https://www.westernsydney.edu.au"
  },
  {
    name: "University of Wollongong",
    location: "Wollongong, New South Wales",
    country: "Australia",
    tuition: "AUD $28,000–$36,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "Computer Science", "Law", "Health Sciences"],
    tag: "Top Ranked",
    website: "https://www.uow.edu.au"
  },
  {
    name: "University of Newcastle",
    location: "Newcastle, New South Wales",
    country: "Australia",
    tuition: "AUD $28,000–$36,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "Medicine", "Education", "Architecture"],
    tag: "Research",
    website: "https://www.newcastle.edu.au"
  },
  {
    name: "Macquarie University",
    location: "Sydney, New South Wales",
    country: "Australia",
    tuition: "AUD $33,000–$40,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.5",
    intakes: "February, July",
    programs: ["Business", "Law", "Science", "Engineering", "Arts"],
    tag: "Top Ranked",
    website: "https://www.mq.edu.au"
  },
  {
    name: "University of Technology Sydney",
    location: "Sydney, New South Wales",
    country: "Australia",
    tuition: "AUD $34,000–$42,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.5",
    intakes: "February, July",
    programs: ["Engineering", "Business", "IT", "Design", "Law"],
    tag: "Technology",
    website: "https://www.uts.edu.au"
  },
  {
    name: "La Trobe University",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $27,000–$34,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Health Sciences", "Business", "Law", "Education", "Engineering"],
    tag: "Health",
    website: "https://www.latrobe.edu.au"
  },
  {
    name: "Swinburne University of Technology",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $30,000–$38,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Engineering", "Business", "Design", "IT", "Psychology"],
    tag: "Technology",
    website: "https://www.swinburne.edu.au"
  },
  {
    name: "Victoria University",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $24,000–$30,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Engineering", "Law", "Sport", "Health Sciences"],
    tag: "Affordable",
    website: "https://www.vu.edu.au"
  },
  {
    name: "Deakin University",
    location: "Geelong, Victoria",
    country: "Australia",
    tuition: "AUD $29,000–$37,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Health", "Engineering", "Education", "IT"],
    tag: "Scholarship",
    website: "https://www.deakin.edu.au"
  },
  {
    name: "University of South Australia",
    location: "Adelaide, South Australia",
    country: "Australia",
    tuition: "AUD $26,000–$34,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Engineering", "Health Sciences", "Architecture", "IT"],
    tag: "Top Ranked",
    website: "https://www.unisa.edu.au"
  },
  {
    name: "Flinders University",
    location: "Adelaide, South Australia",
    country: "Australia",
    tuition: "AUD $26,000–$34,000 / year",
    scholarship: "Up to AUD $8,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Medicine", "Business", "Engineering", "Education", "Law"],
    tag: "Research",
    website: "https://www.flinders.edu.au"
  },
  {
    name: "Torrens University Australia",
    location: "Adelaide, South Australia",
    country: "Australia",
    tuition: "AUD $24,000–$32,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "February, May, July, November",
    programs: ["Business", "Design", "Health", "Hospitality", "IT"],
    tag: "Fast Admissions",
    website: "https://www.torrens.edu.au"
  },
  {
    name: "Bond University",
    location: "Gold Coast, Queensland",
    country: "Australia",
    tuition: "AUD $35,000–$45,000 / year",
    scholarship: "Up to AUD $15,000 / year",
    ielts: "IELTS 6.0",
    intakes: "January, May, September",
    programs: ["Business", "Law", "Health Sciences", "Film", "Architecture"],
    tag: "Scholarship",
    website: "https://www.bond.edu.au"
  },
  {
    name: "Australian Catholic University",
    location: "Sydney, New South Wales",
    country: "Australia",
    tuition: "AUD $24,000–$30,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Nursing", "Education", "Business", "Social Work", "Theology"],
    tag: "Health",
    website: "https://www.acu.edu.au"
  },
  {
    name: "University of Canberra",
    location: "Canberra, ACT",
    country: "Australia",
    tuition: "AUD $26,000–$32,000 / year",
    scholarship: "Up to AUD $5,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Law", "Nursing", "IT", "Design"],
    tag: "Affordable",
    website: "https://www.canberra.edu.au"
  },
  {
    name: "CQUniversity Melbourne",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $22,000–$28,000 / year",
    scholarship: "International merit awards",
    ielts: "IELTS 6.0",
    intakes: "February, July, November",
    programs: ["Business", "IT", "Engineering", "Community Services", "Education"],
    tag: "Fast Admissions",
    website: "https://www.cqu.edu.au"
  },
  {
    name: "TAFE NSW",
    location: "Sydney, New South Wales",
    country: "Australia",
    tuition: "AUD $10,000–$18,000 / year",
    scholarship: "Vocational awards available",
    ielts: "IELTS 5.5",
    intakes: "January, July",
    programs: ["Business", "Hospitality", "IT", "Construction", "Health"],
    tag: "Affordable",
    website: "https://www.tafensw.edu.au"
  },
  {
    name: "Holmes Institute",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $18,000–$24,000 / year",
    scholarship: "Merit scholarships available",
    ielts: "IELTS 5.5",
    intakes: "February, May, July, October",
    programs: ["Business", "Accounting", "HR Management", "Marketing", "IT"],
    tag: "Fast Admissions",
    website: "https://www.holmes.edu.au"
  },
  {
    name: "Think Education (Sydney)",
    location: "Sydney, New South Wales",
    country: "Australia",
    tuition: "AUD $20,000–$26,000 / year",
    scholarship: "Merit awards available",
    ielts: "IELTS 5.5",
    intakes: "February, July",
    programs: ["Business", "Design", "Health", "Education", "IT"],
    tag: "Fast Admissions",
    website: "https://www.think.edu.au"
  },
  {
    name: "Navitas",
    location: "Multiple cities, Australia",
    country: "Australia",
    tuition: "AUD $20,000–$30,000 / year",
    scholarship: "Pathway program awards",
    ielts: "IELTS 5.5",
    intakes: "Multiple per year",
    programs: ["Business", "Engineering", "IT", "Health", "Sciences"],
    tag: "Fast Admissions",
    website: "https://www.navitas.com"
  },
  {
    name: "University of New England",
    location: "Armidale, New South Wales",
    country: "Australia",
    tuition: "AUD $22,000–$28,000 / year",
    scholarship: "International student awards",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Agricultural Science", "Law", "Business", "Education", "Psychology"],
    tag: "Research",
    website: "https://www.une.edu.au"
  },
  {
    name: "Australian National University",
    location: "Canberra, ACT",
    country: "Australia",
    tuition: "AUD $40,000–$48,000 / year",
    scholarship: "Up to AUD $15,000 / year",
    ielts: "IELTS 6.5",
    intakes: "February, July",
    programs: ["Law", "Science", "Engineering", "Business", "Arts"],
    tag: "Top Ranked",
    website: "https://www.anu.edu.au"
  },
  {
    name: "Monash University",
    location: "Melbourne, Victoria",
    country: "Australia",
    tuition: "AUD $38,000–$48,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.5",
    intakes: "February, July",
    programs: ["Medicine", "Engineering", "Business", "Law", "Pharmacy"],
    tag: "Top Ranked",
    website: "https://www.monash.edu"
  },
  {
    name: "Queensland University of Technology",
    location: "Brisbane, Queensland",
    country: "Australia",
    tuition: "AUD $30,000–$38,000 / year",
    scholarship: "Up to AUD $10,000 / year",
    ielts: "IELTS 6.0",
    intakes: "February, July",
    programs: ["Business", "Engineering", "IT", "Design", "Law"],
    tag: "Technology",
    website: "https://www.qut.edu.au"
  },
]

export default universitiesData
